export const CATEGORIES = [
  {
    slug: 'ai-tools',
    name: 'AI Tools',
    description: 'LLMs, image generators, AI coding tools, and machine-learning utilities.',
    iconName: 'Sparkles',
    accentColor: '#8B5CF6',
    displayOrder: 1,
  },
  {
    slug: 'productivity',
    name: 'Productivity',
    description: 'Task managers, note-taking, time trackers, and focus apps.',
    iconName: 'Zap',
    accentColor: '#3B82F6',
    displayOrder: 2,
  },
  {
    slug: 'developer-tools',
    name: 'Developer Tools',
    description: 'APIs, CLIs, testing tools, CI/CD, monitoring, and dev utilities.',
    iconName: 'Code2',
    accentColor: '#10B981',
    displayOrder: 3,
  },
  {
    slug: 'design-tools',
    name: 'Design Tools',
    description: 'UI design, prototyping, icon tools, and creative web apps.',
    iconName: 'Palette',
    accentColor: '#EC4899',
    displayOrder: 4,
  },
  {
    slug: 'marketing',
    name: 'Marketing',
    description: 'Email platforms, SEO tools, social scheduling, and growth software.',
    iconName: 'Megaphone',
    accentColor: '#F59E0B',
    displayOrder: 5,
  },
  {
    slug: 'finance',
    name: 'Finance',
    description: 'Accounting, invoicing, expense tracking, and financial planning.',
    iconName: 'DollarSign',
    accentColor: '#22C55E',
    displayOrder: 6,
  },
  {
    slug: 'analytics',
    name: 'Analytics',
    description: 'Web analytics, dashboards, data visualization, and BI tools.',
    iconName: 'BarChart2',
    accentColor: '#6366F1',
    displayOrder: 7,
  },
  {
    slug: 'collaboration',
    name: 'Collaboration',
    description: 'Team communication, project management, and async tools.',
    iconName: 'Users',
    accentColor: '#F97316',
    displayOrder: 8,
  },
  {
    slug: 'no-code',
    name: 'No-Code',
    description: 'Build web apps, automate workflows, and ship without writing code.',
    iconName: 'Blocks',
    accentColor: '#84CC16',
    displayOrder: 9,
  },
  {
    slug: 'education',
    name: 'Education',
    description: 'LMS platforms, online courses, flashcards, and learning tools.',
    iconName: 'BookOpen',
    accentColor: '#14B8A6',
    displayOrder: 10,
  },
  {
    slug: 'open-source',
    name: 'Open Source',
    description: 'Free, open-source web apps you can self-host or contribute to.',
    iconName: 'Github',
    accentColor: '#94A3B8',
    displayOrder: 11,
  },
  {
    slug: 'security',
    name: 'Security',
    description: 'Password managers, auth tools, vulnerability scanners, and privacy apps.',
    iconName: 'Shield',
    accentColor: '#EF4444',
    displayOrder: 12,
  },
] as const

export type Category = (typeof CATEGORIES)[number]
export type CategorySlug = Category['slug']
